<a href="https://colab.research.google.com/github/mohaseen1/data/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
!nvidia-smi

Thu Sep  7 03:05:33 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Tensors

In [3]:
t1=torch.tensor(1.)
t1

tensor(1.)

In [4]:
type(t1)

torch.Tensor

In [5]:
t1.dtype

torch.float32

In [6]:
##vector

t2=torch.tensor([1.,2,3,4,5])
t2

tensor([1., 2., 3., 4., 5.])

In [7]:
#metrics

t3=torch.tensor([
    [5.,6],
    [6,8],
    [9.,0]


])
t3

tensor([[5., 6.],
        [6., 8.],
        [9., 0.]])

In [8]:
t4=torch.tensor([
    [[11,12,13]],
    [[13,14,15]],
    [[15,16,17]],
    [[18,19,20.]]

                 ])

t4

tensor([[[11., 12., 13.]],

        [[13., 14., 15.]],

        [[15., 16., 17.]],

        [[18., 19., 20.]]])

In [9]:
print (t1)
t1.shape

tensor(1.)


torch.Size([])

In [10]:
print(t2)
t2.shape

tensor([1., 2., 3., 4., 5.])


torch.Size([5])

In [11]:
print(t3)
t3.shape

tensor([[5., 6.],
        [6., 8.],
        [9., 0.]])


torch.Size([3, 2])

In [12]:
print(t4)
t4.shape

tensor([[[11., 12., 13.]],

        [[13., 14., 15.]],

        [[15., 16., 17.]],

        [[18., 19., 20.]]])


torch.Size([4, 1, 3])

In [13]:
t5=torch.tensor([
    [5.,6,11],
    [6,8],
    [9,10,10]


])
t5

ValueError: ignored

In [14]:
#Tensorflow function

In [15]:
t6=torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [16]:
t7=torch.cat((t3,t6))
t7

tensor([[ 5.,  6.],
        [ 6.,  8.],
        [ 9.,  0.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [17]:
t8=torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [-0.2794,  0.9894],
        [ 0.4121,  0.0000],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [18]:
t9=t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [-0.2794,  0.9894]],

        [[ 0.4121,  0.0000],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [19]:
#interroperability with numpy

import numpy as np

In [20]:
x=np.array([[1,2],
           [3,4.]])

x

array([[1., 2.],
       [3., 4.]])

In [21]:
type(x)

numpy.ndarray

In [23]:
y=torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
type(y)

torch.Tensor

In [25]:
y=torch.from_numpy(x)

In [ ]:
y

In [26]:
y.numpy()

array([[1., 2.],
       [3., 4.]])

In [27]:
type(y)

torch.Tensor

## Neural Network using pytorch

In [28]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda, Compose
import matplotlib.pyplot as plt

In [29]:
training_data=datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data=datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100%|██████████| 26421880/26421880 [00:00<00:00, 114807038.11it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 5362568.01it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw




100%|██████████| 4422102/4422102 [00:00<00:00, 63840265.81it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 7932504.41it/s]


Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [30]:
batch_size=64

train_dataloader=DataLoader(training_data,batch_size=batch_size)
test_dataloader=DataLoader(test_data,batch_size=batch_size)

In [31]:
train_dataloader

In [32]:
for x,y in train_dataloader:
  print(x.shape)
  break

torch.Size([64, 1, 28, 28])


In [33]:
device="cuda" if torch.cuda.is_available()else "cpu"
device

'cuda'

In [34]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self) .__init__()
    self.flatten=nn.Flatten()
    self.linear_relu_stack=nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)
    )

  def forward(self,x):
    x=self.flatten(x)
    logits=self.linear_relu_stack(x)
    return logits

In [35]:
model=NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [37]:
loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.SGD(model.parameters(),lr=1e-3)

In [38]:
def train(dataloader,model,loss_fn,optimizer):
  size=len(dataloader.dataset)
  model.train()
  for batch,(x,y) in enumerate(dataloader):
    x,y=x.to(device),y.to(device)

    pred=model(x)
    loss=loss_fn(pred,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100==0:
      loss,current=loss.item(),batch*len(x)
      print(f"loss:{loss:>7f} [{current:>5d}/{size:>5d}]")

In [39]:
def test(dataloader,model,loss_fn):
  size=len(dataloader.dataset)
  num_batches=len(dataloader)
  model.eval()
  test_loss,correct=0,0
  with torch.no_grad():
      for x,y in dataloader:
          x,y=x.to(device),y.to(device)

          pred=model(x)
          test_loss+=loss_fn(pred,y).item()
          correct+=(pred.argmax(1)==y).type(torch.float).sum().item()
  test_loss/=num_batches
  correct/=size
  print(f"Test Error:\n Accuracy:{(100*correct):>0.1f}%,Avg loss:{test_loss:>8f}\n")



In [40]:
epochs=5
for t in range(epochs):
  print(f"Epoch{t+1}\n-------------------------------")
  train(train_dataloader,model,loss_fn,optimizer)
  test(test_dataloader,model,loss_fn)
  print("Done!")



Epoch1
-------------------------------
loss:2.300463 [    0/60000]
loss:2.289970 [ 6400/60000]
loss:2.269503 [12800/60000]
loss:2.265955 [19200/60000]
loss:2.242844 [25600/60000]
loss:2.213082 [32000/60000]
loss:2.223777 [38400/60000]
loss:2.187638 [44800/60000]
loss:2.181285 [51200/60000]
loss:2.150975 [57600/60000]
Test Error:
 Accuracy:47.4%,Avg loss:2.145792

Done!
Epoch2
-------------------------------
loss:2.151462 [    0/60000]
loss:2.143133 [ 6400/60000]
loss:2.084722 [12800/60000]
loss:2.104968 [19200/60000]
loss:2.047106 [25600/60000]
loss:1.993755 [32000/60000]
loss:2.016115 [38400/60000]
loss:1.940026 [44800/60000]
loss:1.938919 [51200/60000]
loss:1.862645 [57600/60000]
Test Error:
 Accuracy:57.6%,Avg loss:1.862307

Done!
Epoch3
-------------------------------
loss:1.899352 [    0/60000]
loss:1.865641 [ 6400/60000]
loss:1.745963 [12800/60000]
loss:1.783236 [19200/60000]
loss:1.677447 [25600/60000]
loss:1.638839 [32000/60000]
loss:1.654989 [38400/60000]
loss:1.564768 [44800/

In [41]:
torch.save(model.state_dict(),"model.pth")
print("saved PyTorch Model State to model.pth")

saved PyTorch Model State to model.pth


In [42]:
model=NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [43]:
## prediction

classes =[
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ancle boot",
]


model.eval()



NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [44]:
x,y=test_data[0][0],test_data[0][1]

In [45]:
x

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,

In [46]:
y

9

In [47]:
with torch.no_grad():
   pred=model(x)
   predicted,actual=classes[pred[0].argmax(0)],classes[y]
   print(f'predicted: "{predicted}",Actual: "{actual}"')

predicted: "Ancle boot",Actual: "Ancle boot"


In [ ]:
#cifar10

In [52]:
import matplotlib.pyplot as plt
import numpy as np
import torchvision

#loop through the training dataloader to get a batch
for images,lables in train_dataloader:
    break #get the first batch and exit loop

    #current the images to numpy arrays
    images=images.numpy()

    #plot the images
    fig,axes=plt.subplots(nrows=4, figsize=(10,10))
    for i, ax in enumerate(axes.flat):
      #display the image
      ax.imshow(np.transpose(images[i],(1,2,0)))
      ax.set_title("Lable:{lables[i].item()}")
      ax.axis('off')

      plt.tight_layout()
      plt.show()